"""empty message

Revision ID: 522fb0f4b831
Revises: f9d79a454a15
Create Date: 2022-05-19 11:18:30.487706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522fb0f4b831'
down_revision = 'f9d79a454a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('related_artist', sa.String(length=150), nullable=False),
    sa.Column('genres', sa.String(length=150), nullable=False),
    sa.Column('images', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('artist')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist')
    # ### end Alembic commands ###
